<?php
function triangle_tracker_menu() {
    $items = array();
    $items['triangle_tracker'] = array(
        'title' => 'triangle tracker',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('triangle_tracker_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
        $items['triangle_success'] = array(
        'title' => 'Ping Pong',
        'page callback' => 'triangle_tracker_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function triangle_tracker_form() {
    $form['first_length'] = array(
        '#title' => 'First Length',
        '#type' => 'textfield',
        '#description' => t('Please enter the length you want.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['second_length'] = array(
        '#title' => 'Second Length',
        '#type' => 'textfield',
        '#description' => t('Please enter the second length you want.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['third_length'] = array(
        '#title' => 'Third Length',
        '#type' => 'textfield',
        '#description' => t('Please enter the third length you want.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );

    return $form;
}

function triangle_tracker_form_submit($form,&$form_state) {
    $first_length = $form_state['values']['first_length'];
    $second_length = $form_state['values']['second_length'];
    $third_length = $form_state['values']['third_length'];
    $output = "string";
    if(($first_length < ($second_length + $third_length)) && ($second_length < ($first_length + $third_length)) && ($third_length < ($second_length + $first_length))) {
        if ($first_length == $second_length || $first_length == $third_length || $third_length == $second_length)
        $output =  "Iscoscele triangle";
        else if (($first_length == $second_length) &&($second_length == $third_length)) {
            $output = "Equilateral";
        }
        else {
            $output = "Scalene Triangle";
        }
    }
    else {
        $output = "Invalid entries try again";
    }
    $_SESSION['type_triangle'] = $output;

    $form_state['redirect'] = 'triangle_success';
}

function triangle_tracker_success() {

    return $_SESSION['type_triangle'];
}
